<?php

/**
 * @file
 * Provides a custom entity types entity type.
 */

declare(strict_types=1);

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function custom_entity_types_theme(): array {
  return [
    'custom_entity_types' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for custom entity types templates.
 *
 * Default template: custom-entity-types.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the custom entity types
 *     information and any fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_custom_entity_types(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function custom_entity_types_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block':
    case 'user_cancel_block_unpublish':
      // Unpublish custom entity types.
      $storage = \Drupal::entityTypeManager()->getStorage('custom_entity_types');
      $custom_entity_types_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(TRUE)
        ->execute();
      custom_entity_types_process_batch($custom_entity_types_ids, 'unPublishNode', 'unPublishNodeFinishedCallback');
      break;

    case 'user_cancel_reassign':
      // Anonymize custom entity types.
      $storage = \Drupal::entityTypeManager()->getStorage('custom_entity_types');
      $custom_entity_types_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(TRUE)
        ->execute();

      custom_entity_types_process_batch($custom_entity_types_ids, 'anonymizeNode', 'anonymizeNodeFinishedCallback');
      break;
  }
}

/**
 * Implements hook_entity_delete().
 */
function custom_entity_types_entity_delete(EntityInterface $entity) {

  if ($entity->getEntityTypeId() === 'user') {
    $uid = $entity->id();
    $storage = \Drupal::entityTypeManager()->getStorage('custom_entity_types');
    $custom_entity_types_ids = $storage->getQuery()
      ->condition('uid', $uid)
      ->accessCheck(TRUE)
      ->execute();

    custom_entity_types_process_batch($custom_entity_types_ids, 'deleteNode', '');
  }
}

/**
 * Process the node id's provided in a batch.
 *
 * @param array $entity_type_ids
 *   Entity Type ids.
 * @param string $op
 *   Operation.
 * @param string $cb
 *   Callback on finishing the batch.
 */
function custom_entity_types_process_batch($entity_type_ids, $op, $cb = ''): void {
  // Process batch by batch.
  $batch = [
    'title' => t('Processing Node...'),
    'init_message' => t('Processing nodes..'),
    'error_message' => t('The nodes could not be processed because an error occurred.'),
    'operations' => [
      [
        '\Drupal\custom_entity_types\BatchOperations::' . $op,
        [$entity_type_ids],
      ],
    ],
    'finished' => '\Drupal\custom_entity_types\BatchOperations::' . $cb,
  ];
  batch_set($batch);
}
